### ISSUE TITLE
keyboard in subpatch blows up Pd

### ISSUE THREAD

**Issue by porres** [porres/pd-keyboard#13]
Unrelarted to my previous blow up bug report

If I have a keyboard object inside a subpatch and this subopatch is closed when I open the patch, then Pd blows up and closes if I click anywhere in the patch, or even in another patch, or even in Pd's terminal window - in short: If Pd receives ANY mouse click action, it blows up!

This doesn't happen if the subpatch is opened when I open the patch, neither when I close the patch subpatch afterwards

**Comment by porres** [comment]
this happens either in vanilla or extended

**Comment by flschiavoni** [comment]
Could not reproduce here. Probably solving issues #7 and #8 solved this issue too.

**Comment by porres** [comment]
that was still happening after those issues were solved. Now it doesn't happen for me with your latest Pull Request, but then the object doesn't work at all as well.

**Comment by porres** [comment]
solved!
