### ISSUE TITLE
tcl/tk errors in vanilla

### ISSUE THREAD

**Issue by porres** [porres/pd-keyboard#3]
I get this when trying to select and move the object in edit mode. This is Vanilla 0.48-0 on macOS 10.12.6

**Comment by porres** [comment]
I get this when clicking in the object while in edit mode

<img width="501" alt="screen shot 2017-10-18 at 19 21 56" src="https://user-images.githubusercontent.com/5360142/31743400-c94ea228-b439-11e7-90bf-9d050ae1873e.png">

**Comment by porres** [comment]
note that I got a "note/velocity" message, which shouldn't happen as I'm in EDIT MODE

**Comment by porres** [comment]
and in edit mode, if I'm trying to select the object, I actually get to play it, see image below

<img width="700" alt="screen shot 2017-10-18 at 20 49 51" src="https://user-images.githubusercontent.com/5360142/31746401-006e9f86-b446-11e7-9cd0-b3fb5bd36cc0.png">

**Comment by porres** [comment]
then, if I release the mouse button, I get the same tcl/tk code again... 

So, since the thing is still active, I can still use it to play and I cannot select it and move it around.

**Comment by porres** [comment]
>  I get the same tcl/tk code again...

not really, I get something else I guess, but it's all chinese anyway
<img width="525" alt="screen shot 2017-10-18 at 20 53 36" src="https://user-images.githubusercontent.com/5360142/31746470-6e64ba20-b446-11e7-9a10-a249fd89861f.png">

**Comment by porres** [comment]
actually the same thing happens in extended, where it still plays the notes when in edit mode. So the particular issue here in vanilla is that it gives you this errors and does not get selected. I'll open a new issue about playing in edit mode

**Comment by danomatika** [comment]
The ".x######.c" refers to a window's canvas where the "x######" is the window id in hex. This error is saying "cannot execute a message to the canvas as the canvas is not found, etc". It might be as simple as sending to the window's canvas ".c" when you want to send to the window only, etc.

**Comment by flschiavoni** [comment]
While we used 
        sys_vgui("**.x%lx.c** create rectangle %d %d %d %d -tags %xrrk%d -fill #000000\n",
to identify the object, on other code part we used 
        sys_vgui("**.x%x.c** create rectangle %d %d %d %d -tags %xSEL -outline blue\n",
I think it is the problem. Solved!

**Comment by porres** [comment]
so, how much of it was "tcl/tk changed and ruined everything" and how much was it "you had it all wrong from the beggining?" :) - and, if it was screwed up from the start, how does it work in the old vanillas?

**Comment by porres** [comment]
fixed!
