### ISSUE TITLE
I can't play the lowest note

### ISSUE THREAD

**Issue by porres** [porres/pd-keyboard#7]
the lowest not possible that I can play on the keyboard is a minor third above the lowest C (Eb)

**Comment by porres** [comment]
this depends on the key width parameter, here the lowest note is much more than a minor third

![save](https://user-images.githubusercontent.com/5360142/32381668-66b10152-c09a-11e7-8955-6cb37832a02a.png)

**Comment by flschiavoni** [comment]
Solved!

**Comment by porres** [comment]
cadê? rs

**Comment by porres** [comment]
This was partially fixed. If you slide through the keyboard, I can "select" and highlight the lowest note, but I can't "play it", here it stops at MIDI note number 50, instead of 48 (C3)

![low note](https://user-images.githubusercontent.com/5360142/32400540-b699acb6-c0e8-11e7-9678-aa9332fcbb42.png)

**Comment by porres** [comment]
this is actually fixed!
